# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a35aff8c899b98f50d81891a5df9598835c9dcd143eb5b96e8d141f7c093e133e30d4cca80ff96ea1e6ccf48317a0ae2bc489fbb509ae1f6123f2710050c7472

test:
  secret_key_base: 88d4abf41dbcdf443aee69afba9358da67cc1d08d77e781de4069a59391942d83163b7b730f062659a22a536c8a0caeef68e5150067034de3f68d7e7a04291a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
